# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ViroSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ViroSample

  target 'ViroSample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ViroSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ViroSample-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ViroSample-tvOS

  target 'ViroSample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
